-- =============================================
-- Migration: 008_create_sales_table.sql
-- Description: Creates the Sales table
-- Dependencies: Patients (FK: PatientID), Users (FK: SoldBy), MedicationRequests (FK: MedicationRequestID)
-- Note: InvoiceNumber is generated by application code, not computed in database
-- =============================================

USE [PharmaCareDB]
GO

PRINT '=============================================';
PRINT 'Creating Sales Table...';
PRINT '=============================================';
GO

-- Drop table if exists (for clean migration)
IF OBJECT_ID('dbo.Sales', 'U') IS NOT NULL
BEGIN
    PRINT 'Dropping existing Sales table...';
    -- Drop dependent table first
    IF OBJECT_ID('dbo.SaleItems', 'U') IS NOT NULL DROP TABLE [dbo].[SaleItems];
    DROP TABLE [dbo].[Sales];
END
GO

-- Create Sales table
CREATE TABLE [dbo].[Sales] (
    [SaleID] INT IDENTITY(1,1) NOT NULL,
    [InvoiceNumber] NVARCHAR(50) NOT NULL,
    [PatientID] INT NULL,
    [TotalAmount] DECIMAL(10,2) NOT NULL,
    [PaymentMethod] NVARCHAR(20) NOT NULL,
    [PaymentStatus] NVARCHAR(20) NOT NULL DEFAULT 'Paid',
    [SoldBy] INT NOT NULL,
    [SaleDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [Notes] NVARCHAR(500) NULL,
    [PaymentReference] NVARCHAR(200) NULL,
    [PaymentDate] DATETIME2 NULL,
    [MedicationRequestID] INT NULL,
    CONSTRAINT [PK_Sales] PRIMARY KEY CLUSTERED ([SaleID] ASC),
    CONSTRAINT [FK_Sales_Patients] FOREIGN KEY ([PatientID]) 
        REFERENCES [dbo].[Patients] ([PatientID]) 
        ON DELETE SET NULL,
    CONSTRAINT [FK_Sales_Users_SoldBy] FOREIGN KEY ([SoldBy]) 
        REFERENCES [dbo].[Users] ([UserID]) 
        ON DELETE RESTRICT,
    CONSTRAINT [FK_Sales_MedicationRequests] FOREIGN KEY ([MedicationRequestID]) 
        REFERENCES [dbo].[MedicationRequests] ([MedicationRequestID]) 
        ON DELETE SET NULL
)
GO

-- Create unique index on InvoiceNumber
CREATE UNIQUE NONCLUSTERED INDEX [IX_Sales_InvoiceNumber] ON [dbo].[Sales] ([InvoiceNumber] ASC)
GO

-- Create indexes
CREATE NONCLUSTERED INDEX [IX_Sales_PatientID] ON [dbo].[Sales] ([PatientID] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Sales_SoldBy] ON [dbo].[Sales] ([SoldBy] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Sales_SaleDate] ON [dbo].[Sales] ([SaleDate] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Sales_PaymentStatus] ON [dbo].[Sales] ([PaymentStatus] ASC)
GO

CREATE NONCLUSTERED INDEX [IX_Sales_MedicationRequestID] ON [dbo].[Sales] ([MedicationRequestID] ASC)
GO

PRINT 'Sales table created successfully!';
GO

-- =============================================
-- DOWN Migration (Rollback)
-- =============================================
-- To rollback this migration, run:
-- DROP TABLE IF EXISTS [dbo].[Sales];
-- =============================================

